from typing import Protocol

class IMessageTransport(Protocol):
    def send(self, data: str) -> None: ...
    def receive(self) -> str: ...

class IMessageHandler(Protocol):
    def handle(self, message: str) -> None: ...
